# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Ковалева Ксения Сергеевна
- АИС-21-1

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |


знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №10
### 1.  Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи

```python
#from functools import lru_cache

#@lru_cache(None)
def fiboonacci(n):
    if n ==0:
        return 0
    elif n == 1:
        return 1
    return fiboonacci(n-1) + fiboonacci(n-2)

if name == 'main':
    print(fiboonacci(100))
```
### Результат.
#### Без декоратора подождала 15 секунд, но так и не дождалась(((
![image](https://github.com/XenKov21/prob/assets/145853363/bc74b43d-ba50-449f-b743-71e061fdb45a)
#### С декоратором, все очень быстро
![image](https://github.com/XenKov21/prob/assets/145853363/f7f6da97-1551-4c10-8ac6-b456e8580569)


### 2. Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что  будет проверять правильность выведенных данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции(имя, возраст_ и проверять чтобы возраст был больше 0 и меньше 130.
Примем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func

@check
def personal_info(name,age):
    print(f"Name:{name}  Age:{age}")

if name == 'main':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138,15,48,2)
```

### Результат.
![image](https://github.com/XenKov21/prob/assets/145853363/96e70e27-de4b-4a1f-902d-0db83fc815a3)



### 3. Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт.
Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.
```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] *15)//10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')

if name == 'main':
    data([1,15, 'Hello', 'i', 'try', 'to', 'crash', 'your','site', 38, 45])
```

### Результат.
![image](https://github.com/XenKov21/prob/assets/145853363/392f8224-9f3c-4554-b013-5c301fff4b7e)


### 4. Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться "Успешная регистрация"

```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name)>10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')


if name == 'main':
    name = '123456789010'
    check_name(name)
```

### Результат.
#### Если строка больше 10 символов:
![image](https://github.com/XenKov21/prob/assets/145853363/7364aa3f-2a1b-45a3-b56b-a45670e41220)
#### Если строка меньше 10 символов:
![image](https://github.com/XenKov21/prob/assets/145853363/a5ae6b47-820d-48c0-ba97-37f17aec9524)


### 5. После запуска сайта вы поняли, что необходимо добавить логгер, для отслеживания его работы. Гтовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: init() (вызывается при создании класса декоратора в программе) и call() (вызыввается при вывозе декоратора). Создайте необходимы вам декоратор. Выведите все логи в консоль

```python
class SiteChecker:
    def init(self, func):
        print('> Класс SiteChecker метод init успешный запуск')
        self.func = func

    def call(self):
        print('> Проверка перед запуском', self.func.name)
        self.func()
        print('>Проверка безопасного выключения')

@SiteChecker
def site():
    print('Усердная работа сайта')

if name == 'main':
    print('>>Сайт запущен')
    site()
    print('>> Сайт выключен')
```

### Результат. 
![image](https://github.com/XenKov21/prob/assets/145853363/50ff3a99-8877-420c-812c-d7914831d7cd)


## Самостоятельная работа №10

### 1. Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time
Декоратор необходимо использовать для этой функции:
def fibonacci():
    fib1 = fib2 = 1

    for i in range(2,200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end = '')

if name== 'main':
    fibonacci()

```python
import time

def calculate_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Function {func.name} took {end_time - start_time} seconds to execute")
        return result
    return wrapper

@calculate_time
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end='')

if name == 'main':
    fibonacci()
```

### Результат. 
![image](https://github.com/XenKov21/prob/assets/145853363/3da1883f-d2ee-48b3-a37d-f7c68a423c2f)


### 2. Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой, что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл бы пустой, то, нужно вызвать исключение ("бросить исключение") и вывести в консоль "файл пустой", а если он не пустой, то вывести информацию из файла

```python
def read_file(filename):
    try:
        with open(filename, 'r') as file:
            data = file.read()
            if not data:
                raise Exception("File is empty")
            else:
                print(data)
    except FileNotFoundError:
        print("File not found")
    except Exception as e:
        print(e)

if name == 'main':
    empty_file = "empty_file.txt"
    non_empty_file = "non_empty_file.txt"

    print("Reading empty file:")
    read_file(empty_file)

    print("\nReading non-empty file:")
    read_file(non_empty_file)
```

### Результат. 
#### Заполненый файл
![image](https://github.com/XenKov21/prob/assets/145853363/55b8e032-ddd3-4c6a-a62b-07177e9e64a5)

#### Пустой файл
![image](https://github.com/XenKov21/prob/assets/145853363/6abd9acc-d8ac-44a7-b7e9-055c4794c969)

#### Результат работы
![image](https://github.com/XenKov21/prob/assets/145853363/0f6c546a-d15b-408c-8be9-ec9e42a565ab)



### 3. Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка "Неподходящий тип данных.Ожидалось число". Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def add_two_numbers():
    try:
        num = input("Enter a number: ")
        result = 2 + int(num)
        print(f"The result is: {result}")
    except ValueError:
        print("Invalid data type. Expected a number")


if name == 'main':
    # Тест 1: ввод числа
    add_two_numbers()

    # Тест 2: ввод строки
    add_two_numbers()
```

### Результат.
![image](https://github.com/XenKov21/prob/assets/145853363/654a4ff0-58dd-45d8-9d1a-b9e9585d13ee)



### 4.  Создайте собственный декоратор, который будет использоваться для двух слов вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
# Создаем класс декоратора
class MultiplyByTwoDecorator:
    def init(self, func):
        self.func = func

    def call(self, *args, **kwargs):
        result = self.func(*args, **kwargs) * 2
        return result

# Создаем две функции, которые будут использовать наш декоратор
@MultiplyByTwoDecorator
def add(a, b):
    return a + b

@MultiplyByTwoDecorator
def multiply(a, b):
    return a * b

# Тестируем функции
print(add(3, 4))  # Результат должен быть 14 (т.к. (3+4)*2=14)
print(multiply(3, 4))  # Результат должен быть 24 (т.к. (3*4)*2=24)
```

### Результат.
#### Комментарии:
1. Я создала класс декоратора MultiplyByTwoDecorator, который принимает функцию и умножает результат этой функции на 2.
2. Далее я создала две функции add и multiply, которые используют этот декоратор.
3. При вызове add(3, 4) результатом будет 14, так как (3+4)*2=14.
4. При вызове multiply(3, 4) результатом будет 24, так как (3*4)*2=24.
Таким образом, я создала собственный декоратор и применили его к двум функциям, получив ожидаемые результаты.
![image](https://github.com/XenKov21/prob/assets/145853363/2454c668-bfba-4b5b-8cb3-040a16110ebe)


### 5. Создайте собственное исключение, которое будет пользоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код в котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода
```python
# Создаем собственное исключение
class ValueTooSmallError(Exception):
    pass

# Фрагмент кода 1: использование исключения
def divide(a, b):
    if b == 0:
        raise ZeroDivisionError("Cannot divide by zero")
    if a < b:
        raise ValueTooSmallError("Value 'a' should be greater than or equal to value 'b'")
    return a / b

try:
    result = divide(5, 2)
    print(result)  # Результат должен быть 2.5
except ZeroDivisionError as e:
    print(e)
except ValueTooSmallError as e:
    print(e)

# Фрагмент кода 2: использование исключения
def calculate_square_root(num):
    if num < 0:
        raise ValueTooSmallError("Cannot calculate square root of a negative number")
    return num ** 0.5

try:
    result = calculate_square_root(25)
    print(result)  # Результат должен быть 5.0
except ValueTooSmallError as e:
    print(e)
```

### Результат. 
#### Комментарии:
1. Я создала собственное исключение ValueTooSmallError.
2. В первом фрагменте кода я использовала это исключение в функции divide, чтобы проверить, что значение 'a' больше или равно значению 'b'.
3. Если условие не выполняется, то возникает исключение ValueTooSmallError.
4. Во втором фрагменте кода я использовала это исключение в функции calculate_square_root, чтобы проверить, что число для извлечения квадратного корня неотрицательное.
5. Если число отрицательное, то возникает исключение ValueTooSmallError.
Таким образом, я создала собственное исключение и использовали его в двух различных фрагментах кода для проверки определенных условий.
![image](https://github.com/XenKov21/prob/assets/145853363/6a26b2c5-0dcc-4e25-8006-848e77e2a068)



## Вывод.
#### Я раньше даже не слышала про декораторы и исключения, очень увлекательно было изучать данную тему. Спасибо!
![image](https://github.com/XenKov21/prob/assets/145853363/f5118c28-da73-4d8f-a3fc-274817053733)
